import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await (await b.newContext({ viewport:{width:1400,height:900} })).newPage()
const errs=[]; p.on('pageerror',e=>errs.push(String(e).slice(0,200)))
await p.goto('http://127.0.0.1:4173/')
await p.evaluate(() => localStorage.setItem('dcsimu:account:session:v1','dcsimu-admin'))
await p.goto('http://127.0.0.1:4173/admin', { waitUntil:'networkidle' })
await p.getByRole('button', { name:'Biblioteca 3D' }).first().click()
await p.waitForTimeout(600)
await p.getByRole('searchbox').first().fill('LOGO')
await p.waitForTimeout(800)
await p.getByRole('button', { name:/^Editar( no 3D)?$/ }).first().click()
await p.waitForTimeout(12000)
await p.screenshot({ path:'/home/user/logo.png' })
console.log('url', p.url(), 'erros', errs.join('|')||'0')
await b.close()
