import { chromium, devices } from 'playwright'
const b = await chromium.launch()
const p = await (await b.newContext(devices['iPhone 13'])).newPage()
const errs=[]; p.on('pageerror',e=>errs.push(String(e.stack||e).slice(0,600)))
p.on('response', r => { if (r.status()>=400) errs.push('HTTP '+r.status()+' '+r.url().slice(0,120)) })
await p.goto('https://dc-simu.vercel.app/', { waitUntil:'domcontentloaded', timeout:60000 })
await p.evaluate(() => localStorage.setItem('dcsimu:account:session:v1','dcsimu-admin'))
await p.goto('https://dc-simu.vercel.app/admin', { waitUntil:'networkidle', timeout:60000 })
console.log('admin texto:', (await p.innerText('body')).slice(0,150).replace(/\n/g,' | '))
await p.getByRole('button', { name:'Biblioteca 3D' }).first().click().catch(e=>console.log('sem separador', String(e).slice(0,80)))
await p.waitForTimeout(1500)
await p.getByRole('button', { name:/^Editar( no 3D)?$/ }).first().click().catch(e=>console.log('sem botao editar', String(e).slice(0,80)))
await p.waitForTimeout(12000)
console.log('url', p.url(), 'ce-root', await p.locator('.ce-root').count(), 'canvas', await p.locator('canvas').count())
console.log('texto:', (await p.innerText('body')).slice(0,200).replace(/\n/g,' | '))
await p.screenshot({ path:'/home/user/shot-prod.png' })
console.log('erros:', errs.join('\n').slice(0,1500)||'0')
await b.close()
