import { chromium, devices } from 'playwright'
const b = await chromium.launch()
const p = await (await b.newContext(devices['iPhone 13'])).newPage()
const errs=[]; p.on('pageerror',e=>errs.push(String(e).slice(0,300)))
await p.goto('http://127.0.0.1:4173/')
await p.evaluate(() => localStorage.setItem('dcsimu:account:session:v1','dcsimu-admin'))
await p.goto('http://127.0.0.1:4173/admin', { waitUntil:'networkidle' })
await p.getByRole('button', { name:'Biblioteca 3D' }).first().click()
await p.waitForTimeout(600)
await p.getByRole('searchbox').first().fill('DM-20')
await p.waitForTimeout(700)
await p.getByRole('button', { name:/^Editar( no 3D)?$/ }).first().click()
await p.waitForTimeout(11000)
await p.screenshot({ path:'/home/user/rib-closed.png' })
await p.screenshot({ path:'/home/user/rib-open.png', clip:{x:0,y:0,width:390,height:260} })
console.log('erros', errs.join('|')||'0')
await b.close()
