import { chromium, devices } from 'playwright'
const b = await chromium.launch()
const p = await (await b.newContext(devices['iPhone 13'])).newPage()
const errs=[]; p.on('pageerror',e=>errs.push(String(e).slice(0,300)))
await p.goto('http://127.0.0.1:4173/')
await p.evaluate(() => localStorage.setItem('dcsimu:account:session:v1','dcsimu-admin'))
await p.goto('http://127.0.0.1:4173/admin', { waitUntil:'networkidle' })
await p.getByRole('button', { name:'Biblioteca 3D' }).first().click()
await p.waitForTimeout(600)
await p.getByRole('button', { name:/^Editar( no 3D)?$/ }).first().click()
await p.waitForTimeout(9000)
await p.screenshot({ path:'/home/user/view-barra.png' })
await p.locator('.ce-viewbar.is-compact .ce-tool', { hasText: 'Vista' }).click()
await p.waitForTimeout(600)
await p.screenshot({ path:'/home/user/view-menu.png' })
console.log('erros', errs.join('|')||'0')
await b.close()
